version: 2
build:
  os: ubuntu-22.04  # TODO: can I remove this?
  tools:
    python: '3.8'
python:
  system_packages: true
  install:
    - method: pip
      path: .
      extra_requirements: [ docs ]
sphinx: # TODO: can I remove this?
  configuration: docs/conf.py
