version: 2
build:
  os: ubuntu-22.04
  tools:
    python: '3.8'
#  jobs:
#    post_install:
#      - pip install poetry==1.3.1
#      - poetry config virtualenvs.create false
#      - poetry install --sync
python:
  install:
    - method: pip
      path: .
