#!/bin/bash
# Developer tools

# Create the Python virtual environment used for development
run_env() {
   deactivate 2>/dev/null  # just in case a virtual environment is active

   if [ $# -gt 0 ] && [ $1 == "rebuild" ]; then
      if [ -d .python ]; then
         echo "Rebuilding virtual environment from scratch..."
         rm -rf .python
      else
         echo "Creating virtual environment..."
      fi
   else
      if [ -d .python ]; then
         echo "Updating virtual environment..."
      else
         echo "Creating virtual environment..."
      fi
   fi

   virtualenv --quiet --download .python
   source .python/bin/activate

   VERSION=`python version.py`
   DEPENDENCIES=`python dependencies.py`

   echo "Installing dependencies for $VERSION:\n$DEPENDENCIES"
   pip install --quiet $DEPENDENCIES
}

# Run the unit tests
run_test() {
   PYTHONPATH=src/ pytest $* unittest
}

# Render a board via the render script
run_render() {
   PYTHONPATH=src/ src/scripts/render
}

# Run one of the developer tools
case $1 in
   env)
      shift 1
      run_env $*
      ;;
   test)
      shift 1
      run_test $*
      ;;
   render)
      run_render
      ;;
   *)
      echo "Unknown command $1"
      exit 1
esac

