#!/usr/bin/env python
# -*- coding: utf-8 -*-
# vim: set ft=python ts=4 sw=4 expandtab:
# Run a game with simulated players, displaying output on the terminal

from apologies.cli import cli

cli("demo")
