#!/usr/bin/env python
# -*- coding: utf-8 -*-
# vim: set ft=python ts=3 sw=3 expandtab:
# Render a game on the terminal, for development purposes

from apologies.render import render_board
from apologies.game import Game

game = Game(4)
board = render_board(game)
print(board, end="")
