#!/usr/bin/env python
# -*- coding: utf-8 -*-
# vim: set ft=python ts=4 sw=4 expandtab:
# Run a simulation to see how well different character input sources behave

from apologies.cli import cli

cli("simulation")
