name: Install Poetry
description: Install the Poetry build tool
inputs:
  version:
    description: "Version of Poetry to install (>= 1.2.0)"
    required: true
runs:
  using: composite
  env:
    POETRY_HOME: "${{ env.GITHUB_WORKSPACE }}/.poetry/runtime"
    POETRY_CACHE: "{{ env.GITHUB_WORKSPACE }}/.poetry/cache"
    POETRY_VERSION: "${{ inputs.version }}"
  steps:
    - name: Install Poetry
      shell: bash
      run: |
        "$GITHUB_ACTION_PATH/scripts/install-poetry.sh"
    - name: Add Poetry to the system $PATH
      shell: bash
      run: |
        # Add Poetry to the system $PATH
        echo "$POETRY_HOME/bin" >> "$GITHUB_PATH"
    - name: Disable the Python keyring
      shell: bash
      run: |
        # Disable the Python keyring
        # This prevents Poetry from using the Python keyring, which sometimes fails or hangs on Linux
        # See: https://github.com/python-poetry/poetry/issues/2692#issuecomment-1235683370
        echo "PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring" >> "$GITHUB_ENV"
    - name: Configure Poetry
      shell: bash
      run: |
        # Configure Poetry to use a local cache and virtual environment
        poetry config cache-dir "$POETRY_CACHE" --local
        poetry config virtualenvs.create true --local
        poetry config virtualenvs.in-project true --local
         
