name: Install Poetry
description: Install the Poetry build tool
inputs:
  version:
    description: "Version of Poetry to install (>= 1.2.0)"
    required: true
runs:
  using: composite
  steps:
    - name: Install Poetry
      shell: bash
      env:
        POETRY_HOME: "${{ github.workspace }}/.poetry/runtime"
        POETRY_VERSION: "${{ inputs.version }}"
      run: |
        # Install Poetry >=1.2.0 using the official installer
        "$GITHUB_ACTION_PATH/scripts/install-poetry.sh"
    - name: Add Poetry to the system $PATH
      shell: bash
      run: |
        # Add Poetry to the system $PATH
        echo "$GITHUB_WORKSPACE/.poetry/runtime/bin" >> "$GITHUB_PATH"
    - name: Check Poetry location and version
      shell: bash
      run: |
        # Check Poetry location and version
        which poetry
        poetry --version
    - name: Configure Poetry
      shell: bash
      run: |
        # Configure Poetry to use a local cache and virtual environment
        poetry config cache-dir "$GITHUB_WORKSPACE/.poetry/cache" --local
        poetry config virtualenvs.create true --local
        poetry config virtualenvs.in-project true --local
        poetry config --list
    - name: Disable the Python keyring
      shell: bash
      run: |
        # Disable the Python keyring
        # This prevents Poetry from using the Python keyring, which sometimes fails or hangs on Linux
        # See: https://github.com/python-poetry/poetry/issues/2692#issuecomment-1235683370
        echo "PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring" >> "$GITHUB_ENV"
