name: Install Poetry
description: Install the Poetry build tool
inputs:
  version:
    description: "Version of Poetry to install (>= 1.2.0)"
    required: true
runs:
  using: composite
  steps:
    - name: Set Poetry environment variables
      shell: bash
      run: |
        # Set Poetry environment variables
        echo "${{ inputs.version }}" >> "$POETRY_VERSION"
        echo "$GITHUB_WORKSPACE/.poetry/runtime" >> "$POETRY_HOME"
        echo "$GITHUB_WORKSPACE/.poetry/cache" >> "$POETRY_CACHE"
    - name: Install Poetry
      shell: bash
      run: |
        # Install Poetry >=1.2.0 using the official installer
        "$GITHUB_ACTION_PATH/scripts/install-poetry.sh"
    - name: Add Poetry to the system $PATH
      shell: bash
      run: |
        # Add Poetry to the system $PATH
        echo "$GITHUB_WORKSPACE/.poetry/runtime/bin" >> "$GITHUB_PATH"
    - name: Configure Git to ignore Poetry install
      shell: bash
      run: |
        # Configure Git to ignore the Poetry install
        echo "*" > "$POETRY_HOME/.gitignore"
        echo "*" > "$POETRY_CACHE/.gitignore"
    - name: Dump Poetry location and version
      shell: bash
      run: |
        # Dump Poetry location and version
        which poetry
        poetry --version
    - name: Configure Poetry
      shell: bash
      run: |
        # Configure Poetry to use a local cache and virtual environment
        poetry config cache-dir "$GITHUB_WORKSPACE/.poetry/cache" --local
        poetry config virtualenvs.create true --local
        poetry config virtualenvs.in-project true --local
        poetry config --list
    - name: Disable the Python keyring
      shell: bash
      run: |
        # Disable the Python keyring
        # This prevents Poetry from using the Python keyring, which sometimes fails or hangs on Linux
        # See: https://github.com/python-poetry/poetry/issues/2692#issuecomment-1235683370
        echo "PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring" >> "$GITHUB_ENV"
